QALI-471: Display the step meters in the console live report
qalipsis/qalipsis-plugin-redis-lettuce pull request #13
Opened 2023-08-16 08:28 UTC by oceenachi

2023-08-17 06:49 UTC, ericjesse requested changes

2023-08-17 06:49 UTC, ericjesse commented on redis-lettuce/src/main/kotlin/io/qalipsis/plugins/redis/lettuce/poll/converters/PollResultSetBatchConverter.kt
> +            failureCounter?.increment(bytes.toDouble())
Do you want to count the failed bytes or records? I would rather count the failed records

2023-08-17 06:49 UTC, ericjesse commented on redis-lettuce/src/main/kotlin/io/qalipsis/plugins/redis/lettuce/poll/converters/PollResultSetSingleConverter.kt
> +    private var failureCounter: Counter? = null
The failure here does not make a lot of sense, because we are "reading" the data from the DB, so there is nothing that we try to convert that fails, that is interesting for the meters. Meters are for IO attempts and failures, not for conversion ones (when both operation are decoupled).

Same applies to the next converter.

2023-08-17 11:05 UTC, oceenachi commented on redis-lettuce/src/main/kotlin/io/qalipsis/plugins/redis/lettuce/poll/converters/PollResultSetSingleConverter.kt
> +    private var failureCounter: Counter? = null
Okay.
Does this apply to the converters of r2dbc-jasync plugin. E.g the ResultSetSingleConverter, JasyncResultSetBatchConverter and ResultSetBatchConverter?

2023-08-18 09:31 UTC, ericjesse commented on redis-lettuce/src/main/kotlin/io/qalipsis/plugins/redis/lettuce/poll/converters/PollResultSetSingleConverter.kt
> +    private var failureCounter: Counter? = null
Yes, it does.

2023-08-22 18:19 UTC, ericjesse approved these changes

2023-08-23 03:55 UTC, merged